[theme]
primaryColor = "#1f77b4"
backgroundColor = "#e6b2b2ff"
secondaryBackgroundColor = "#718abdff"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
showErrorDetails = true

[logger]
level = "info"

[client]
caching = true
displayEnabled = true
showErrorDetails = true
